### PR TITLE
pricing util implementation and corresponding test

### PR DESCRIPTION
**Pull request by daniel-majcher**
Implemented the PricingUtil class. Tested the new class. Additionally confirmed that module was successfully created and imported with pybind by running Driver. Unit tests make sure that calcval and getval both give expected consistent results and correctly update when calcval is called.

### CODE REVIEW

**Comment by minnce** [comment]
image
Please fix

**Review by minnce — CHANGES_REQUESTED** [review]
Please fix

**Comment by daniel-majcher** [comment]
> image Please fix

strange i dont get this error on my end

**Comment by minnce** [comment]
LGTM

**Comment by echavemann** [comment]
pls merge + update main repo

**Pull request merged**
